### ISSUE TITLE
サムネがほしい

### ISSUE THREAD

**Issue by 75asa** [takanakahiko/tweet-deleter#21]
デフォルトでなかひこくんのアイコンが出ているが、 tweet-deleter 専用の画像がほしい…

**Comment by 75asa** [comment]
@takanakahiko かわいい画像ありがとうございます！！
あと最後この画像をリポジトリの og image に設定してもらえると感無量です！
FYI: https://codehex.hateblo.jp/entry/2019/04/18/114028

**Comment by takanakahiko** [comment]
READMEに追加したタイミングで設定してまっせ！

**Comment by takanakahiko** [comment]
@75asa 
蛇足かもですが twitter が持っている OGP のキャッシュはここから更新することができます
https://cards-dev.twitter.com/validator

**Comment by 75asa** [comment]
> @75asa 
> 蛇足かもですが twitter が持っている OGP のキャッシュはここから更新することができます
> https://cards-dev.twitter.com/validator
> 

知見でした！
ありがとうございます！！
キャッシュ更新後 DM でも確認できました👍
